### PR TITLE
Serialisation (WIP)

### PR DESCRIPTION
**Pull request by lionel-**
Includes https://github.com/tidyverse/rlang/pull/210

Like `serialize()` and `unserialize()` with better handling of closures and formulas:

- closure/formula body is scanned to determine where symbols are scoped
- if scoped within the search path, the relevant package envs are recorded
- when unserialised, a fake search path is reconstituted around the closure/formula
- a fake global environment is also reconstituted but only with relevant objects

### CODE REVIEW

**Comment by hadley** [comment]
I think we should make these functions generic — that's a major limitation with the existing serialize functions.

I think copying related objects from the global env should be an option.

**Comment by javierluraschi** [comment]
@lionel- While doing some testing, found out this:

```r
rlanglabs::serialise_bytes(function(df) {
  apply(df, 1, function(x) {
  })
})
```

triggers:

```
Error in FUN(X[[i]], ...) : invalid first argument
Called from: FUN(X[[i]], ...)

34: FUN(X[[i]], ...)
33: vapply(.x, .f, .mold, ..., USE.NAMES = FALSE)
32: map_mold(.x, .f, logical(1), ...)
31: map_lgl(nms, exists, envir = get_env(env), inherits = inherit)
30: env_has(env, nm) at serial.R#168
29: binding_env(nm, env) at env.R#92
28: env_type(binding_env(nm, env)) at serial.R#145
27: search_symbol_bindings(syms, expr, env)
26: switch_type(expr, symbol = search_symbol_bindings(syms, expr, 
        env), language = search_language_bindings(syms, expr, env), 
        pairlist = search_pairlist_bindings(syms, expr, env)) at serial.R#137
25: search_expr_bindings(syms, node_car(expr), env) at serial.R#161
24: search_pairlist_bindings(syms, expr, env)
```

but this one `serialize()` works correctly:

```r
serialize(function(df) {
  apply(df, 1, function(x) {
  })
})
```

**Comment by javierluraschi** [comment]
@lionel- probably same issue, or a variation...

```r
rlanglabs::serialise_bytes(function(df) {
  for (idx in nrow(df)) {
    df[idx, ]
  }
})
```

```
Error in FUN(X[[i]], ...) : invalid first argument
```

**Comment by javierluraschi** [comment]
@lionel- Looks like my comment above is caused by empty symbols, say `serialise_bytes(df[1, ])`, if it helps, sending a fix your way: https://github.com/lionel-/rlanglabs/pull/2/files#diff-32b5ac86d032c7e7a26f17e5fba585ccR147

**Comment by hadley** [comment]
Can we also record package versions so we can warn if different on unserialize?

**Comment by javierluraschi** [comment]
@lionel- just found this one, haven't investigated yet:

```r
rlanglabs::serialise_bytes(function() .libPaths())
```

```
Error: `nm` must be `NULL` or a character vector the same length as `x`
```

**Comment by lionel-** [comment]
Thanks I'll take a look tomorrow.

Also I was thinking that we may need a different approach for the cases where a serialised function refer to other functions in its enclosure. Ideally all closures would be serialised the same way.

**Comment by javierluraschi** [comment]
Another one, the repro is a bit hard, this works fine:

```r
rlanglabs::serialise_bytes(function(e) rprojroot::find_rstudio_root_file())
```

However, if I run ^^^ and then move to a different machine with all the same libraries (but potentially not all loaded in the same way), I get:

```r
list(
  message = "could not find function \"is_reference\"",
  call = closureRLang(closureRLangRaw)
)
```

This does not trigger with `serialize()`. I can work on a better repo if this error is not obvious.

Also, should I be opening bugs instead? Maybe we merge this PR into `rlanglabs` as it is and I open bugs for the issues I find?

Also, a more complex closure (see [sparkwarc.R#L63-L86](https://github.com/javierluraschi/sparkwarc/blob/feature/spark-apply-rcpp/R/sparkwarc.R#L63-L86)), is triggering the following:

```r
list(
  message = "could not find function \"mut_env_parent\"",
  call = .f(x, y, ...)) 
```

I can work on a better repro, but sending your way first in case this looks familiar enough.

**Comment by lionel-** [comment]
I'll make UI adjustments regarding Hadley's comments then I'll merge. But you can post issues thanks! I think I'll debug these functions next week by feeding them a large namespace coerced to an ordinary environment.

**Comment by lionel-** [comment]
> However, if I run ^^^ and then move to a different machine with all the same libraries (but potentially not all loaded in the same way), I get:

Ah, there's actually a simple explanation :) this PR depends on this branch of rlang: https://github.com/tidyverse/rlang/pull/210

**Comment by lionel-** [comment]
@hadley I made them generics, but I think we need another sort of genericity. We should be serialising all instances of an object in the same way, not just the one that is supplied to `serialise_bytes()`. However we probably can't use S3 dispatch to solve this because this wouldn't be efficient. This issue connects to the need for C-level dispatch that we encountered in several other places.

**Pull request merged**
